version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "4306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/sweet-spot
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    depends_on:
      - db
    stdin_open: true
    tty: true
