services:
  - type: web
    name: dictionary
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C ./config/puma.rb ./config.ru"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false