# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  password: password
  username: root
  host: db

development:
  <<: *default
  adapter: mysql2
  database: sweet-spot_development

test:
  <<: *default
  database: sweet-spot_test
  host: <%= ENV.fetch("APP_DATABASE_HOST") { 'db' } %>

production:
  <<: *default
  database: sweet-spot_production
  username: <%= ENV['DB_USERNAME_PROD'] %>
  host: <%= ENV['DB_HOST_PROD'] %>
  password: <%= ENV['DB_PASSWORD_PROD'] %>
  ssl_mode: verify_identity
  sslca: "/etc/ssl/certs/ca-certificates.crt"
