# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  password: password
  username: root
  host: db

development:
  <<: *default
  database: sweet-spot_development

test:
  <<: *default
  database: sweet-spot_test
  host: <%= ENV.fetch("APP_DATABASE_HOST") { 'db' } %>

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
